use anyhow::{Context, Result};
use std::collections::HashMap;
use std::path::Path;

/// Generates the `embedded.rs` file that gets included by the runner's main.rs.
/// This file contains static byte arrays for the manifest, assets, and archives.
pub fn generate_embedded_rs(
    manifest_yaml: &str,
    logo_bytes: &[u8],
    banner_bytes: &[u8],
    icon_bytes: &[u8],
    archives: &HashMap<String, Vec<u8>>,
    output_path: &Path,
) -> Result<()> {
    log::info!("Generating embedded.rs → {}", output_path.display());

    let archive_map_json = serde_json::to_vec(archives)
        .context("Failed to serialize archive map")?;

    let manifest_escaped = bytes_to_rust_byte_literal(manifest_yaml.as_bytes());
    let logo_escaped     = bytes_to_rust_byte_literal(logo_bytes);
    let banner_escaped   = bytes_to_rust_byte_literal(banner_bytes);
    let icon_escaped     = bytes_to_rust_byte_literal(icon_bytes);
    let archive_escaped  = bytes_to_rust_byte_literal(&archive_map_json);

    let total_payload_kb = (logo_bytes.len() + banner_bytes.len() + icon_bytes.len()
        + archives.values().map(|v| v.len()).sum::<usize>()) / 1024;

    let content = format!(
        r#"// ── Auto-generated by iebuild — DO NOT EDIT ────────────────────────────────
// Total embedded payload: {} KB

/// Raw bytes of installer.yaml
pub static MANIFEST_YAML: &[u8] = {};

/// Raw bytes of the logo PNG (may be empty)
pub static ASSET_LOGO: &[u8] = {};

/// Raw bytes of the banner PNG (may be empty)
pub static ASSET_BANNER: &[u8] = {};

/// Raw bytes of the app icon (may be empty)
pub static ASSET_ICON: &[u8] = {};

/// JSON-serialized HashMap<String, Vec<u8>> of Zstd-compressed tar archives
pub static ARCHIVE_MAP: &[u8] = {};
"#,
        total_payload_kb,
        manifest_escaped,
        logo_escaped,
        banner_escaped,
        icon_escaped,
        archive_escaped,
    );

    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(output_path, content)
        .with_context(|| format!("Write failed: {}", output_path.display()))?;

    log::info!("embedded.rs written ({} KB total payload)", total_payload_kb);
    Ok(())
}

/// Format raw bytes as a Rust byte-string literal: b"\x00\x01..."
fn bytes_to_rust_byte_literal(data: &[u8]) -> String {
    if data.is_empty() {
        return "b\"\"".to_string();
    }
    let mut out = String::with_capacity(data.len() * 4 + 3);
    out.push_str("b\"");
    for &b in data {
        match b {
            b'"'  => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(b as char),
            _ => out.push_str(&format!("\\x{:02x}", b)),
        }
    }
    out.push('"');
    out
}

/// Read an optional asset file — returns empty Vec if file doesn't exist.
pub fn read_optional_asset(base_dir: &Path, rel_path: Option<&str>) -> Vec<u8> {
    if let Some(p) = rel_path {
        let full = base_dir.join(p);
        match std::fs::read(&full) {
            Ok(data) => {
                log::info!("Asset loaded: {} ({} bytes)", full.display(), data.len());
                data
            }
            Err(e) => {
                log::warn!("Asset not found or unreadable: {} — {}", full.display(), e);
                Vec::new()
            }
        }
    } else {
        Vec::new()
    }
}